(** Generated stylesheets for one property, drawn from {!Value_gen}.

    {!Value_gen} writes one declaration at a time, so nothing it draws reaches a
    pass that decides about a declaration by looking at another one: shorthand
    contraction, duplicate elimination, rule merging and the canonical
    projection all need a second declaration before they do anything at all.
    This draws those shapes.

    A generated sheet carries the simpler sheets it is built from. A pass that
    is wrong about one declaration is wrong about every sheet containing it, so
    an oracle that already reported the part does not report the composite as a
    second finding. That is the same provenance {!Value_gen.vector} carries for
    a respelling, one level up. *)

type sheet = {
  css : string;
  parts : string list;
      (** the simpler sheets this one is built from, each a member of this same
          population *)
}

val sheets_for : seed:int -> string -> sheet list
(** [sheets_for ~seed name] is the sheets to try for property [name]. Every
    sample is a function of [seed] and [name], so a finding is regenerated by
    repeating the command that found it.

    One declaration on its own, that declaration beside a value of the same
    property, beside a value of a property whose name says they share a grammar,
    behind a custom property, split across two rules, and wrapped in the
    conditional groups whose contents the optimizer treats as one run. *)

val partners : string -> string list
(** [partners name] is the properties whose declarations can write a slot [name]
    writes, judged from the names alone: CSS names a longhand by extending its
    shorthand with a hyphen. Read from the manifest rather than from the
    library, so the library does not choose its own test population. *)
