(** Generated CSS values for one property, drawn from the spec-derived manifest
    in this same library.

    A value generator is a source of test input rather than a fact about
    browsers, so it sits here where more than one oracle can draw the same
    population: the accept-set harness asks a browser about these values, and
    the read-back sweep asks cascade whether it can read what it printed of
    them. *)

val values_for : seed:int -> string -> string list
(** [values_for ~seed name] is the values to try against property [name]. Every
    sample is a function of [seed] and [name], so a finding is regenerated by
    repeating the command that found it.

    The pools mix the property's own manifest vectors, a neighbouring property's
    (the last hyphen-separated segment names the grammar far more often than the
    first does), a sample of every value the manifest writes anywhere, and
    shapes no grammar shares: CSS-wide keywords, substitutions, degenerate text
    and malformed values. Every value is writable into a declaration block, so
    none carries a [;], a brace or a newline. *)

val wildcards : string list
(** [wildcards] is the pool asked of every property. Nothing here claims any
    property takes any of them. *)
