(* Generated CSS values for one property, drawn from the spec-derived manifest
   in this same library.

   Every sample is a function of the seed and the property name, so a finding is
   regenerated by repeating the command that found it. The pools mix the
   property's own vectors, a neighbouring property's (the last hyphen-separated
   segment names the grammar far more often than the first does), a sample of
   every value the manifest writes anywhere, and shapes no grammar shares:
   CSS-wide keywords, substitutions, degenerate text and malformed values.

   Extracted from the accept-set harness so more than one oracle can draw the
   same population: a value generator is a source of test input rather than a
   fact about browsers, and the read-back sweep wants it too. *)

(* ===== A seeded stream ===== *)

(* Every sample this run draws is a function of the seed and the property name,
   so a finding is regenerated by repeating the command that found it. *)

let mask = 0x3FFFFFFF

let seed_of ~seed name =
  let h = ref (((seed * 0x9E3779B1) + 0x85EBCA6B) land mask) in
  String.iter (fun c -> h := ((!h * 33) + Char.code c) land mask) name;
  !h

type stream = { mutable state : int }

let stream n = { state = n land mask lor 1 }

let next s =
  s.state <- ((s.state * 1103515245) + 12345) land mask;
  s.state

(* Fisher-Yates over a copy, so a sample is a subset in a stable order and the
   pool it came from is untouched. *)
let sample s n values =
  let a = Array.of_list values in
  let len = Array.length a in
  for i = len - 1 downto 1 do
    let j = next s mod (i + 1) in
    let t = a.(i) in
    a.(i) <- a.(j);
    a.(j) <- t
  done;
  Array.to_list (Array.sub a 0 (min n len))

(* ===== Value pools ===== *)

(* Asked of every property. Nothing here claims any property takes any of them:
   these are the shapes a reader lets through by accident, and about half are
   the initial value of some property somewhere, which is the other direction of
   the same question. The browser says which property takes which. *)
let wildcards =
  [
    "auto";
    "none";
    "normal";
    "0";
    "1";
    "10px";
    "50%";
    "red";
    "currentcolor";
    "1s";
    "45deg";
    "url(a.png)";
    "\"text\"";
    "center";
    "both";
    "content-box";
    "min-content";
    "infinite";
    "ease";
    "hidden";
  ]

(* CSS Cascade 5 sec. 7: every property takes each of these. *)
let css_wide = [ "initial"; "inherit"; "unset"; "revert"; "revert-layer" ]

(* CSS Variables 1 sec. 3: a declaration with a var() is valid at parse time
   whatever the property, because substitution happens later. *)
let substitutions = [ "var(--x)"; "var(--x, 10px)"; "var(--x) var(--y)" ]

(* A value that is not there at all. *)
let degenerate = [ ""; " "; "\t" ]

(* Wrong shapes: an unknown identifier, a unit that is not one, a magnitude past
   what any property takes, and punctuation where a component belongs. *)
let malformed =
  [
    "cascade-not-a-keyword";
    "10zz";
    "1e999px";
    "-99999999px";
    "99999999999";
    "-1";
    "200%";
    "10 %";
    "10px 20px 30px 40px 50px";
    ",";
    "10px,";
  ]

(* ===== The manifest as a value source ===== *)

(* The spec-derived vectors of test/spec/inventory. They are read here as
   values, never as verdicts: what this run wants from them is CSS text that
   somebody wrote down for a real grammar, which is what makes a neighbouring
   property's vector worth trying. *)
let manifest = Property_grammar.rows

let row_of =
  let table = Hashtbl.create 512 in
  List.iter
    (fun (r : Property_grammar.row) -> Hashtbl.replace table r.property r)
    manifest;
  fun name -> Hashtbl.find_opt table name

(* The last hyphen-separated segment names the grammar far more often than the
   first does: -color, -style, -width, -image, -duration. Properties sharing one
   are the neighbours whose values are worth crossing over. *)
let last_segment name =
  match String.rindex_opt name '-' with
  | Some i when i + 1 < String.length name ->
      String.sub name (i + 1) (String.length name - i - 1)
  | Some _ | None -> name

let by_segment =
  let table = Hashtbl.create 256 in
  List.iter
    (fun (r : Property_grammar.row) ->
      let key = last_segment r.property in
      let previous = try Hashtbl.find table key with Not_found -> [] in
      Hashtbl.replace table key (r :: previous))
    manifest;
  table

let neighbours name =
  let key = last_segment name in
  let rows = try Hashtbl.find by_segment key with Not_found -> [] in
  List.concat_map
    (fun (r : Property_grammar.row) ->
      if String.equal r.property name then [] else r.positives)
    rows

(* Every value the manifest writes down anywhere. A sample of it gives each
   property a few vectors from a grammar nothing relates to its own, which is
   the widest form of the same question. *)
let universe =
  List.sort_uniq String.compare
    (List.concat_map (fun (r : Property_grammar.row) -> r.positives) manifest)

(* ===== Generating a property's values ===== *)

(* A value has to survive being written into a declaration block, so anything
   carrying the block's own punctuation is not a value this run can ask
   about. *)
let writable value =
  not
    (String.exists
       (fun c ->
         Char.equal c ';' || Char.equal c '{' || Char.equal c '}'
         || Char.equal c '\n')
       value)

let single_component value =
  (not (String.equal value ""))
  && not
       (String.exists
          (fun c -> Char.equal c ' ' || Char.equal c ',' || Char.equal c '\t')
          value)

(* Repetition is where the box grammars live, and where a reader that counts
   components loosely shows it. The parts come from the property's own grammar
   and its neighbours', so the result is a plausible shape rather than noise. *)
let repetitions s pool =
  let singles = Array.of_list (List.filter single_component pool) in
  let len = Array.length singles in
  if len < 2 then []
  else
    let pick () = singles.(next s mod len) in
    let join n = String.concat " " (List.init n (fun _ -> pick ())) in
    [ join 2; join 3; join 4; String.concat ", " [ pick (); pick () ] ]

let neighbour_count = 10
let universe_count = 8

let values_for ~seed name =
  let s = stream (seed_of ~seed name) in
  let own =
    match row_of name with
    | None -> []
    | Some r -> List.concat [ r.positives; r.negatives ]
  in
  let near = sample s neighbour_count (neighbours name) in
  let far = sample s universe_count universe in
  let pool = List.concat [ own; near; far; wildcards ] in
  let generated =
    List.concat
      [
        wildcards;
        css_wide;
        substitutions;
        degenerate;
        malformed;
        own;
        near;
        far;
        repetitions s pool;
      ]
  in
  List.sort_uniq String.compare (List.filter writable generated)
