(** Generated CSS values for one property, drawn from the spec-derived manifest
    in this same library.

    A value generator is a source of test input rather than a fact about
    browsers, so it sits here where more than one oracle can draw the same
    population: the accept-set harness asks a browser about these values, and
    the read-back sweep asks cascade whether it can read what it printed of
    them. *)

type vector = { value : string; respells : string option }
(** A generated value, and the value it respells when it is one.

    CSS Syntax 3 sec. 4 turns escapes, comments and whitespace into tokens and
    CSS Values 4 sec. 4.1 matches keywords ASCII case-insensitively, so a
    respelling and the value it respells are one value to any conforming reader.
    An oracle that already knows why two implementations differ about the
    original therefore knows why they differ here, and does not have to call the
    respelling a second, separate finding. Only the token-level respellings
    carry an origin: a value wrapped in a math function, put beside a [var()] or
    repeated past its grammar's bound is a different value. *)

val vectors_for : seed:int -> string -> vector list
(** [vectors_for ~seed name] is {!values_for} with that provenance kept. *)

val values_for : seed:int -> string -> string list
(** [values_for ~seed name] is the values to try against property [name]. Every
    sample is a function of [seed] and [name], so a finding is regenerated by
    repeating the command that found it.

    The pools mix the property's own manifest vectors, a neighbouring property's
    (the last hyphen-separated segment names the grammar far more often than the
    first does), a sample of every value the manifest writes anywhere, and
    shapes no grammar shares: CSS-wide keywords, substitutions, degenerate text
    and malformed values. A grammar whose value is a sequence of identifiers
    reserves a name by position rather than by presence, so a reserved name of
    the property's own grammar is also written beside a name from somebody
    else's, in both orders. Every value is writable into a declaration block, so
    none carries a [;], a brace or a newline. *)

val wildcards : string list
(** [wildcards] is the pool asked of every property. Nothing here claims any
    property takes any of them. *)
