(** Tests for Css_tools.Css_compare module *)

open Cascade

let () = ignore Css.of_string

(* ===== compare tests ===== *)

let compare_identical () =
  let css = ".a { color: red }" in
  Alcotest.(check bool) "identical CSS compares true" true
    (Css_tools.Css_compare.compare css css)

let compare_different () =
  Alcotest.(check bool) "different CSS compares false" false
    (Css_tools.Css_compare.compare ".a { color: red }" ".a { color: blue }")

let compare_empty () =
  Alcotest.(check bool) "empty strings compare true" true
    (Css_tools.Css_compare.compare "" "")

let compare_whitespace_difference () =
  (* Structurally same but different formatting - compare requires string
     equality too *)
  let css1 = ".a { color: red }" in
  let css2 = ".a{color:red}" in
  (* These are structurally the same but strings differ, so compare returns
     false *)
  Alcotest.(check bool) "whitespace-different CSS" false
    (Css_tools.Css_compare.compare css1 css2)

(* ===== diff returning No_diff ===== *)

let diff_no_diff () =
  let css = ".a { color: red }" in
  let result = Css_tools.Css_compare.diff ~expected:css ~actual:css in
  match result with
  | Css_tools.Css_compare.No_diff -> ()
  | _ -> Alcotest.fail "expected No_diff"

let diff_no_diff_empty () =
  let result = Css_tools.Css_compare.diff ~expected:"" ~actual:"" in
  match result with
  | Css_tools.Css_compare.No_diff -> ()
  | _ -> Alcotest.fail "expected No_diff for empty strings"

(* ===== diff returning Tree_diff ===== *)

let diff_tree_diff () =
  let expected = ".a { color: red }" in
  let actual = ".a { color: blue }" in
  let result = Css_tools.Css_compare.diff ~expected ~actual in
  match result with
  | Css_tools.Css_compare.Tree_diff d ->
      Alcotest.(check bool) "tree diff is not empty" false
        (Css_tools.Tree_diff.is_empty d)
  | _ -> Alcotest.fail "expected Tree_diff"

let diff_tree_diff_added_rule () =
  let expected = ".a { color: red }" in
  let actual = ".a { color: red } .b { margin: 0 }" in
  let result = Css_tools.Css_compare.diff ~expected ~actual in
  match result with
  | Css_tools.Css_compare.Tree_diff _ -> ()
  | _ -> Alcotest.fail "expected Tree_diff for added rule"

(* ===== diff returning String_diff ===== *)

let diff_string_diff () =
  (* To trigger String_diff, we need structurally identical CSS that differs
     only in formatting. This is tricky because the parser normalizes things.
     We use diff_with_mode with `String to force it. *)
  let expected = ".a { color: red }" in
  let actual = ".a  { color: red }" in
  let result =
    Css_tools.Css_compare.diff_with_mode ~mode:`String ~expected ~actual
  in
  match result with
  | Css_tools.Css_compare.String_diff d ->
      Alcotest.(check bool) "string diff has position" true (d.position >= 0)
  | Css_tools.Css_compare.No_diff ->
      (* Strings might be considered equal after strip_header/trim *)
      ()
  | _ -> Alcotest.fail "expected String_diff or No_diff"

(* ===== diff returning parse errors ===== *)

let diff_actual_error () =
  let expected = ".a { color: red }" in
  let actual = ".a { color: }" in
  let result = Css_tools.Css_compare.diff ~expected ~actual in
  (* The parser may or may not error on this - just check it doesn't crash *)
  ignore result

let diff_expected_error () =
  let expected = ".a { color: }" in
  let actual = ".a { color: red }" in
  let result = Css_tools.Css_compare.diff ~expected ~actual in
  ignore result

(* ===== strip_header tests ===== *)

let strip_header_no_header () =
  let css = ".a { color: red }" in
  Alcotest.(check string) "no header unchanged" css
    (Css_tools.Css_compare.strip_header css)

let strip_header_with_header () =
  let css = "/*! Generated by tool v1.0 */\n.a { color: red }" in
  let result = Css_tools.Css_compare.strip_header css in
  Alcotest.(check string) "header stripped" ".a { color: red }" result

let strip_header_regular_comment () =
  let css = "/* regular comment */\n.a { color: red }" in
  let result = Css_tools.Css_compare.strip_header css in
  (* Regular comments (not /*!) should NOT be stripped *)
  Alcotest.(check string) "regular comment preserved"
    "/* regular comment */\n.a { color: red }" result

let strip_header_empty () =
  Alcotest.(check string) "empty string" ""
    (Css_tools.Css_compare.strip_header "")

let strip_header_only_header () =
  let css = "/*! header only */" in
  let result = Css_tools.Css_compare.strip_header css in
  Alcotest.(check string) "only header stripped" "" result

(* ===== stats tests ===== *)

let stats_no_diff () =
  let css = ".a { color: red }" in
  let result = Css_tools.Css_compare.diff ~expected:css ~actual:css in
  let s =
    Css_tools.Css_compare.stats ~expected_str:css ~actual_str:css result
  in
  Alcotest.(check int) "expected chars" (String.length css) s.expected_chars;
  Alcotest.(check int) "actual chars" (String.length css) s.actual_chars;
  Alcotest.(check int) "added rules" 0 s.added_rules;
  Alcotest.(check int) "removed rules" 0 s.removed_rules;
  Alcotest.(check int) "modified rules" 0 s.modified_rules;
  Alcotest.(check int) "reordered rules" 0 s.reordered_rules;
  Alcotest.(check int) "container changes" 0 s.container_changes

let stats_with_tree_diff () =
  let expected = ".a { color: red }" in
  let actual = ".a { color: red } .b { margin: 0 }" in
  let result = Css_tools.Css_compare.diff ~expected ~actual in
  let s =
    Css_tools.Css_compare.stats ~expected_str:expected ~actual_str:actual result
  in
  Alcotest.(check int) "expected chars" (String.length expected) s.expected_chars;
  Alcotest.(check int) "actual chars" (String.length actual) s.actual_chars;
  (* With a tree diff, at least one of added/removed/modified should be > 0 *)
  let total = s.added_rules + s.removed_rules + s.modified_rules in
  Alcotest.(check bool) "has rule changes" true (total > 0)

let pp_stats_does_not_crash () =
  let css = ".a { color: red }" in
  let result = Css_tools.Css_compare.diff ~expected:css ~actual:css in
  let s =
    Css_tools.Css_compare.stats ~expected_str:css ~actual_str:css result
  in
  let buf = Buffer.create 256 in
  let fmt = Format.formatter_of_buffer buf in
  Css_tools.Css_compare.pp_stats fmt s;
  Format.pp_print_flush fmt ();
  let output = Buffer.contents buf in
  Alcotest.(check bool) "pp_stats produces output" true
    (String.length output > 0)

(* ===== diff_with_mode tests ===== *)

let diff_with_mode_auto () =
  let expected = ".a { color: red }" in
  let actual = ".a { color: blue }" in
  let result =
    Css_tools.Css_compare.diff_with_mode ~mode:`Auto ~expected ~actual
  in
  match result with
  | Css_tools.Css_compare.Tree_diff _ -> ()
  | _ -> Alcotest.fail "expected Tree_diff in auto mode"

let diff_with_mode_tree () =
  let expected = ".a { color: red }" in
  let actual = ".a { color: blue }" in
  let result =
    Css_tools.Css_compare.diff_with_mode ~mode:`Tree ~expected ~actual
  in
  match result with
  | Css_tools.Css_compare.Tree_diff _ -> ()
  | _ -> Alcotest.fail "expected Tree_diff in tree mode"

let diff_with_mode_string () =
  let expected = ".a { color: red }" in
  let actual = ".a { color: blue }" in
  let result =
    Css_tools.Css_compare.diff_with_mode ~mode:`String ~expected ~actual
  in
  match result with
  | Css_tools.Css_compare.String_diff _ -> ()
  | Css_tools.Css_compare.No_diff -> ()
  | _ -> Alcotest.fail "expected String_diff or No_diff in string mode"

let diff_with_mode_string_identical () =
  let css = ".a { color: red }" in
  let result =
    Css_tools.Css_compare.diff_with_mode ~mode:`String ~expected:css ~actual:css
  in
  match result with
  | Css_tools.Css_compare.No_diff -> ()
  | _ -> Alcotest.fail "expected No_diff for identical in string mode"

(* ===== as_tree_diff tests ===== *)

let as_tree_diff_with_tree () =
  let expected = ".a { color: red }" in
  let actual = ".a { color: blue }" in
  let result = Css_tools.Css_compare.diff ~expected ~actual in
  Alcotest.(check bool) "as_tree_diff returns Some for Tree_diff" true
    (Option.is_some (Css_tools.Css_compare.as_tree_diff result))

let as_tree_diff_no_diff () =
  let css = ".a { color: red }" in
  let result = Css_tools.Css_compare.diff ~expected:css ~actual:css in
  Alcotest.(check bool) "as_tree_diff returns None for No_diff" true
    (Option.is_none (Css_tools.Css_compare.as_tree_diff result))

(* ===== pp tests ===== *)

let pp_does_not_crash () =
  let expected = ".a { color: red }" in
  let actual = ".a { color: blue }" in
  let result = Css_tools.Css_compare.diff ~expected ~actual in
  let buf = Buffer.create 256 in
  let fmt = Format.formatter_of_buffer buf in
  Css_tools.Css_compare.pp fmt result;
  Format.pp_print_flush fmt ();
  (* Just verify it doesn't crash *)
  ignore (Buffer.contents buf)

(* ===== Suite ===== *)

let suite =
  ( "css_compare",
    [
      Alcotest.test_case "compare identical" `Quick compare_identical;
      Alcotest.test_case "compare different" `Quick compare_different;
      Alcotest.test_case "compare empty" `Quick compare_empty;
      Alcotest.test_case "compare whitespace difference" `Quick
        compare_whitespace_difference;
      Alcotest.test_case "diff No_diff" `Quick diff_no_diff;
      Alcotest.test_case "diff No_diff empty" `Quick diff_no_diff_empty;
      Alcotest.test_case "diff Tree_diff" `Quick diff_tree_diff;
      Alcotest.test_case "diff Tree_diff added rule" `Quick
        diff_tree_diff_added_rule;
      Alcotest.test_case "diff String_diff" `Quick diff_string_diff;
      Alcotest.test_case "diff actual error" `Quick diff_actual_error;
      Alcotest.test_case "diff expected error" `Quick diff_expected_error;
      Alcotest.test_case "strip_header no header" `Quick strip_header_no_header;
      Alcotest.test_case "strip_header with header" `Quick
        strip_header_with_header;
      Alcotest.test_case "strip_header regular comment" `Quick
        strip_header_regular_comment;
      Alcotest.test_case "strip_header empty" `Quick strip_header_empty;
      Alcotest.test_case "strip_header only header" `Quick
        strip_header_only_header;
      Alcotest.test_case "stats no diff" `Quick stats_no_diff;
      Alcotest.test_case "stats with tree diff" `Quick stats_with_tree_diff;
      Alcotest.test_case "pp_stats does not crash" `Quick pp_stats_does_not_crash;
      Alcotest.test_case "diff_with_mode auto" `Quick diff_with_mode_auto;
      Alcotest.test_case "diff_with_mode tree" `Quick diff_with_mode_tree;
      Alcotest.test_case "diff_with_mode string" `Quick diff_with_mode_string;
      Alcotest.test_case "diff_with_mode string identical" `Quick
        diff_with_mode_string_identical;
      Alcotest.test_case "as_tree_diff with tree" `Quick as_tree_diff_with_tree;
      Alcotest.test_case "as_tree_diff with no diff" `Quick
        as_tree_diff_no_diff;
      Alcotest.test_case "pp does not crash" `Quick pp_does_not_crash;
    ] )
