(** The web-features Baseline dataset, as data.

    Generated by [scripts/gen_baseline.sh]; regenerate when browsers ship new
    features. {!Support} is what asks questions of it. *)

val greenfield_properties : string list
(** CSS property names whose owning web-features feature is not Baseline "widely
    available". A vendor-prefixed declaration whose unprefixed twin names one of
    these keeps its prefix, since a maintained browser may read only the
    prefixed form. The list is conservative: web-features tracks a feature's
    full support, so a long-established property (e.g. [background-attachment])
    appears when a recent value of it is not yet widely available. *)

type version = int * int
(** A browser version as [(major, minor)], the leading [major.minor] of what
    web-features records. *)

type support = {
  chrome : version option;
  firefox : version option;
  safari : version option;
  safari_ios : version option;
}
(** The first version of each engine that shipped a production. [None] is an
    engine that does not implement it at all. *)

val dataset_version : string
(** The web-features release {!support} was generated from. *)

val support : (string * support) list
(** Per-engine first versions, keyed by BCD compat key
    ([css.properties.text-overflow.string]). Every [css.*] key web-features
    records is listed, so a production absent from it is one web-features does
    not model rather than one nothing implements. *)
