(library
 (public_name cascade)
 (name cascade)
 (flags
  (:standard -w -9))
 (libraries uutf psq logs unix))

(mdx
 (files
  aria.mli
  baseline.mli
  block.mli
  color_space.mli
  common.mli
  component.mli
  container.mli
  context.mli
  cover.mli
  css.mli
  css_graph.mli
  cursor.mli
  ctx.mli
  declaration.mli
  error.mli
  edge.mli
  factor.mli
  font_face.mli
  inline.mli
  index.mli
  keyframe.mli
  lexer.mli
  loc.mli
  loop.mli
  media.mli
  merge.mli
  nest.mli
  optimize.mli
  factor_safe.mli
  flatten.mli
  parser.mli
  pool.mli
  preflight.mli
  pp.mli
  properties.mli
  reader.mli
  resolve.mli
  rule.mli
  rule_index.mli
  selector.mli
  shorthand.mli
  size.mli
  sort.mli
  stats.mli
  stylesheet.mli
  summary.mli
  supports.mli
  syntax.mli
  token.mli
  weighted_interval.mli
  values.mli
  variables.mli)
 (libraries cascade))
