#!/bin/sh
# Regenerate lib/baseline.ml from the web-features Baseline dataset.
#
# An unprefixed declaration supersedes its vendor-prefixed twin only once every
# maintained browser reads it. A feature that is Baseline "widely available"
# (in every maintained engine for ~30 months) is safe to assume; anything less,
# "newly available" or "limited", is not. This emits the CSS property names that
# are NOT yet "widely available", so lib/shorthand.ml keeps exactly those
# prefixes.
#
# The source (https://github.com/web-platform-dx/web-features) is the machine-
# checkable Baseline dataset. Rerun this when browsers ship new features:
#
#   scripts/gen_baseline.sh && dune fmt
#
# Requires curl and jq.
set -eu

url=https://unpkg.com/web-features
data=$(curl -sfL "$url/data.json")
version=$(curl -sfL "$url/package.json" | jq -r .version)

# Names, under BCD prefix $1, of a single [a-z-] segment (i.e. the property
# itself, not a sub-value like [anchor-name.none]). A name counts as greenfield
# only when it is covered by a not-"high" feature AND by no "high" feature,
# otherwise an established property (e.g. accent-color) is picked up just
# because a newer feature also references it.
greenfield() {
  printf '%s' "$data" | jq -r --arg p "$1" '
    def names(cond):
      [ .features[]
        | select(cond)
        | (.compat_features // [])[]
        | select(startswith($p + ".") and (ltrimstr($p + ".") | test("^[a-z-]+$")))
        | ltrimstr($p + ".") ]
      | unique;
    (names(.status.baseline != "high") - names(.status.baseline == "high"))
    | .[]'
}

to_ocaml() {
  while IFS= read -r n; do
    [ -n "$n" ] && printf '    "%s";\n' "$n"
  done
}

{
  printf '(* Generated by scripts/gen_baseline.sh from web-features %s.\n' "$version"
  printf '   CSS properties that are not yet Baseline "widely available"\n'
  printf '   (web-features status.baseline other than "high"), so a vendor-prefixed\n'
  printf '   declaration naming one of them keeps its prefix. Do not edit by hand;\n'
  printf '   rerun scripts/gen_baseline.sh when browsers update. *)\n\n'
  printf 'let greenfield_properties =\n  [\n'
  greenfield css.properties | to_ocaml
  printf '  ]\n'
} >lib/baseline.ml

echo "wrote lib/baseline.ml from web-features $version"
