#!/bin/sh
# Regenerate lib/baseline.ml from the web-features Baseline dataset.
#
# An @supports (or feature-query) guard is written to detect a feature that a
# browser might not support. A feature that is Baseline "widely available"
# (in every maintained engine for ~30 months) is safe to assume, so its guard
# can be dropped; anything less than that -- "newly available" or "limited" --
# must keep its guard. This emits the CSS property and value-function names that
# are NOT yet "widely available", so lib/supports.ml keeps exactly those guards.
#
# The source (https://github.com/web-platform-dx/web-features) is the machine-
# checkable Baseline dataset. Rerun this when browsers ship new features:
#
#   scripts/gen_baseline.sh && dune fmt
#
# Requires curl and jq.
set -eu

url=https://unpkg.com/web-features
data=$(curl -sfL "$url/data.json")
version=$(curl -sfL "$url/package.json" | jq -r .version)

# Names, under BCD prefix $1, of a single [a-z-] segment (i.e. the property or
# function itself, not a sub-value like [anchor-name.none]). A name counts as
# greenfield only when it is covered by a not-"high" feature AND by no "high"
# feature -- otherwise an established property (e.g. accent-color) is picked up
# just because a newer feature also references it.
greenfield() {
  printf '%s' "$data" | jq -r --arg p "$1" '
    def names(cond):
      [ .features[]
        | select(cond)
        | (.compat_features // [])[]
        | select(startswith($p + ".") and (ltrimstr($p + ".") | test("^[a-z-]+$")))
        | ltrimstr($p + ".") ]
      | unique;
    (names(.status.baseline != "high") - names(.status.baseline == "high"))
    | .[]'
}

to_ocaml() {
  while IFS= read -r n; do
    [ -n "$n" ] && printf '    "%s";\n' "$n"
  done
}

{
  printf '(* Generated by scripts/gen_baseline.sh from web-features %s.\n' "$version"
  printf '   CSS properties and value functions that are not yet Baseline\n'
  printf '   "widely available" (web-features status.baseline other than "high"),\n'
  printf '   whose feature-query guards are load-bearing and must be kept. Do not\n'
  printf '   edit by hand; rerun scripts/gen_baseline.sh when browsers update. *)\n\n'
  printf 'let greenfield_properties =\n  [\n'
  greenfield css.properties | to_ocaml
  printf '  ]\n\n'
  printf 'let greenfield_value_functions =\n  [\n'
  greenfield css.types | to_ocaml
  printf '  ]\n'
} >lib/baseline.ml

echo "wrote lib/baseline.ml from web-features $version"
