(* Does cascade agree with a browser about which at-rule conditions apply?

   [@media], [@supports] and [@container] preludes decide whether a whole block
   applies. Cascade answers that question in [Context.matches_media],
   [Context.matches_supports] and [Context.matches_container]; it answers a
   second one, whether two conditions mean the same thing, in [Media.equal] and
   [Container.equal], which gate block merging, and in [Media.lower_for_minify],
   which rewrites a prelude under minify. A wrong answer to either silently
   includes or excludes a whole block, and nothing was checking either against a
   browser.

   The questions are asked apart.

   Evaluation. The environment is not assumed: the page reads back what the
   browser says it is - the viewport, the resolution, and every discrete feature
   it recognises - and the query context cascade is asked about is built out of
   that reading. A plain feature the reading supplies is definitionally agreed;
   what the population is for is everything above it, the ranges, the negations,
   the [and]/[or] chains, the comma lists, the media types, the boolean forms
   and the features no browser recognises.

   Rewriting. [Media.lower_for_minify] and [Media.normalize] claim to preserve
   which media a query selects. That claim is checked without cascade evaluating
   anything: the browser answers the query as written and as rewritten, in every
   environment, and the two answers have to be one answer.

   Merging. [Media.equal] is documented as "true only when [a] and [b] select
   the same media", and it gates block merging. So for every pair it calls equal
   the browser must give one answer in every environment. An environment sits at
   each boundary the population names, and on both sides of it, because that is
   where an off-by-one lives.

   Two independent oracles answer each condition, as test/spec/browser's runs
   ask them: [matchMedia] and an [@media] rule that sets a custom property the
   probe's computed style is read for. A condition they disagree about is a fact
   about the browser rather than about cascade, and is reported rather than
   decided.

   Skips cleanly, with status 0, when node or a headless Chromium is missing.

   Reproducing one finding:

   dune exec test/render/at_rule_conditions.exe -- --only '(monochrome)' dune
   exec test/render/at_rule_conditions.exe -- --seed 3

   Showing the run is not blind:

   dune exec test/render/at_rule_conditions.exe -- --plant evaluation dune exec
   test/render/at_rule_conditions.exe -- --plant rewrite dune exec
   test/render/at_rule_conditions.exe -- --plant merge *)

open Cascade

let ( // ) = Filename.concat

(* ===== A seeded stream ===== *)

(* Every compound this run draws is a function of the seed, so a finding is
   regenerated by repeating the command that found it. *)

let mask = 0x3FFFFFFF

type stream = { mutable state : int }

let stream n = { state = n land mask lor 1 }

let next s =
  s.state <- ((s.state * 1103515245) + 12345) land mask;
  s.state

let pick s = function [] -> "" | l -> List.nth l (next s mod List.length l)

(* ===== The environments ===== *)

(* An environment is a set of command-line flags, because nothing it moves can
   be changed from inside the page. The widths and heights sit on the boundaries
   the condition population names and on both sides of them. *)

type env = { env_id : string; label : string; flags : string list }

let viewport w h =
  String.concat "" [ "--window-size="; string_of_int w; ","; string_of_int h ]

let environments =
  let sized w h extra =
    {
      env_id = "";
      label =
        String.concat ""
          [
            string_of_int w;
            "x";
            string_of_int h;
            (match extra with [] -> "" | _ -> " ");
            String.concat " " extra;
          ];
      flags = viewport w h :: extra;
    }
  in
  List.mapi
    (fun i e -> { e with env_id = string_of_int i })
    [
      sized 320 640 [];
      sized 399 600 [];
      sized 400 600 [];
      sized 401 600 [];
      sized 600 800 [];
      sized 640 480 [];
      sized 800 600 [];
      sized 1024 768 [];
      sized 1280 1024 [];
      sized 800 600 [ "--force-device-scale-factor=2" ];
      sized 800 600 [ "--blink-settings=preferredColorScheme=0" ];
      sized 800 600 [ "--force-prefers-reduced-motion" ];
    ]

(* ===== The media population ===== *)

let width_values =
  [
    "0";
    "0px";
    "320px";
    "399px";
    "400px";
    "401px";
    "600px";
    "640px";
    "800px";
    "1024px";
    "25em";
    "40em";
    "50rem";
  ]

let height_values =
  [ "0px"; "480px"; "599px"; "600px"; "601px"; "768px"; "30em" ]

(* One bound in each of the spellings Media Queries 4 sec. 2.4.3 and sec. 2.4.4
   give it, plus the equality forms. *)
let bounds name values =
  List.concat_map
    (fun v ->
      List.map
        (fun parts -> String.concat "" parts)
        [
          [ "(min-"; name; ": "; v; ")" ];
          [ "(max-"; name; ": "; v; ")" ];
          [ "("; name; ": "; v; ")" ];
          [ "("; name; " >= "; v; ")" ];
          [ "("; name; " > "; v; ")" ];
          [ "("; name; " <= "; v; ")" ];
          [ "("; name; " < "; v; ")" ];
          [ "("; name; " = "; v; ")" ];
          [ "("; v; " <= "; name; ")" ];
          [ "("; v; " > "; name; ")" ];
        ])
    values

(* A lower bound and an upper bound on one feature: the pair
   [Media.lower_for_minify] folds into the two-sided interval, written both ways
   round and with each combination of strict and inclusive. *)
let bound_pairs =
  List.concat_map
    (fun (name, lo, hi) ->
      List.map
        (fun parts -> String.concat "" parts)
        [
          [ "(min-"; name; ": "; lo; ") and (max-"; name; ": "; hi; ")" ];
          [ "(max-"; name; ": "; hi; ") and (min-"; name; ": "; lo; ")" ];
          [ "("; name; " > "; lo; ") and ("; name; " <= "; hi; ")" ];
          [ "("; name; " >= "; lo; ") and ("; name; " < "; hi; ")" ];
          [ "("; lo; " <= "; name; ") and ("; name; " <= "; hi; ")" ];
          [ "not ((min-"; name; ": "; lo; ") and (max-"; name; ": "; hi; "))" ];
        ])
    [
      ("width", "400px", "800px");
      ("width", "400px", "400px");
      ("width", "800px", "400px");
      ("width", "0px", "1024px");
      ("width", "25em", "50em");
      ("height", "480px", "600px");
      ("resolution", "1dppx", "2dppx");
      ("aspect-ratio", "1/1", "2/1");
      ("color", "1", "8");
      ("color-index", "1", "5");
      ("monochrome", "0", "5");
      ("cascade-unknown", "3px", "9px");
    ]

let intervals =
  [
    "(400px <= width <= 800px)";
    "(400px < width < 800px)";
    "(800px >= width >= 400px)";
    "(400px <= width < 800px)";
    "(800px > width >= 400px)";
    "(480px <= height <= 600px)";
    "(1dppx <= resolution <= 2dppx)";
  ]

let discrete =
  [
    "(orientation: portrait)";
    "(orientation: landscape)";
    "(orientation: sideways)";
    "(prefers-color-scheme: dark)";
    "(prefers-color-scheme: light)";
    "(prefers-color-scheme: no-preference)";
    "(prefers-reduced-motion: reduce)";
    "(prefers-reduced-motion: no-preference)";
    "(prefers-contrast: more)";
    "(prefers-contrast: no-preference)";
    "(prefers-reduced-transparency: reduce)";
    "(prefers-reduced-data: reduce)";
    "(forced-colors: active)";
    "(forced-colors: none)";
    "(inverted-colors: inverted)";
    "(hover: hover)";
    "(hover: none)";
    "(any-hover: hover)";
    "(pointer: fine)";
    "(pointer: coarse)";
    "(any-pointer: none)";
    "(update: fast)";
    "(update: slow)";
    "(scan: progressive)";
    "(scan: interlace)";
    "(color-gamut: srgb)";
    "(color-gamut: p3)";
    "(dynamic-range: standard)";
    "(dynamic-range: high)";
    "(display-mode: browser)";
    "(display-mode: fullscreen)";
    "(overflow-block: scroll)";
    "(overflow-block: none)";
    "(overflow-inline: scroll)";
    "(scripting: enabled)";
    "(scripting: none)";
    "(nav-controls: back)";
  ]

(* Media Queries 4 sec. 2.4.2: a boolean feature is false when its value is zero
   or none, which is a different question from whether the environment has the
   feature at all. *)
let booleans =
  [
    "(width)";
    "(height)";
    "(resolution)";
    "(aspect-ratio)";
    "(color)";
    "(color-index)";
    "(monochrome)";
    "(grid)";
    "(orientation)";
    "(hover)";
    "(any-hover)";
    "(pointer)";
    "(update)";
    "(scripting)";
    "(prefers-color-scheme)";
    "(prefers-reduced-motion)";
    "(forced-colors)";
    "(display-mode)";
    "(cascade-unknown)";
  ]

let numerics =
  [
    "(color: 8)";
    "(color: 0)";
    "(min-color: 1)";
    "(color >= 8)";
    "(color-index: 0)";
    "(min-color-index: 1)";
    "(monochrome: 0)";
    "(min-monochrome: 1)";
    "(grid: 0)";
    "(grid: 1)";
    "(resolution: 1dppx)";
    "(resolution: 2dppx)";
    "(min-resolution: 1dppx)";
    "(min-resolution: 2dppx)";
    "(resolution >= 2dppx)";
    "(resolution: 96dpi)";
    "(min-resolution: 192dpi)";
    "(resolution: 1x)";
    "(min-resolution: 2x)";
    "(aspect-ratio: 4/3)";
    "(aspect-ratio: 1/1)";
    "(min-aspect-ratio: 1/1)";
    "(aspect-ratio >= 1/1)";
    "(aspect-ratio < 1)";
    "(aspect-ratio: 1)";
    "(horizontal-viewport-segments: 1)";
    "(vertical-viewport-segments: 1)";
  ]

(* Media Queries 4 sec. 3.1: a grammatical but unrecognised query is
   [<general-enclosed>], whose result is unknown, and a malformed one is false.
   Neither is an error. *)
let unrecognised =
  [
    "(cascade-unknown: 1)";
    "(min-cascade-unknown: 3px)";
    "(cascade-unknown > 3px)";
    "not (cascade-unknown: 1)";
    "not (cascade-unknown)";
    "(cascade-unknown: 1) or (min-width: 1px)";
    "(cascade-unknown: 1) and (min-width: 1px)";
    "not (scan: progressive)";
    "(width: banana)";
    "(width: -1px)";
    "(min-width: -10px)";
    "(min-width)";
    "(width: 400)";
    "(400px)";
    "(width >= banana)";
    "(orientation: 3)";
    "(width:)";
    "()";
  ]

(* Media Queries 4 sec. 3.1: a feature name the grammar knows, carrying a value
   it does not admit, still matches [<general-enclosed>], so the query stays
   valid and its result is unknown. Three-valued logic then decides the
   enclosing condition, and unknown beside a settled operand is not the same
   answer as dropping the query. Each shape puts one such feature beside an
   operand that is true in every environment and one that is false in all of
   them, and under a negation, because that is where the two answers part. *)
let unknown_atoms =
  [
    "(cascade-unknown: 1)";
    "(min-cascade-unknown: 3px)";
    "(orientation: sideways)";
    "(orientation: 3)";
    "(width: banana)";
    "(width: 400)";
    "(scan: progressive)";
    "(inverted-colors: inverted)";
  ]

let settled_atoms = [ "(min-width: 0px)"; "(min-width: 99999px)" ]

let recovery =
  List.concat
    [
      List.concat_map
        (fun u ->
          List.concat_map
            (fun f ->
              List.map
                (fun parts -> String.concat "" parts)
                [
                  [ u; " and "; f ];
                  [ u; " or "; f ];
                  [ "not ("; u; " and "; f; ")" ];
                  [ "not ("; u; " or "; f; ")" ];
                ])
            settled_atoms)
        unknown_atoms;
      List.map (fun u -> String.concat "" [ "not "; u ]) unknown_atoms;
    ]

let types =
  [
    "all";
    "screen";
    "print";
    "tv";
    "speech";
    "cascade-medium";
    "not screen";
    "not print";
    "not all";
    "not tv";
    "only screen";
    "only print";
    "only all";
    "screen and (min-width: 400px)";
    "print and (min-width: 400px)";
    "not screen and (min-width: 400px)";
    "not all and (min-width: 400px)";
    "not all and (cascade-unknown: 1)";
    "only screen and (max-width: 600px)";
    "all and (min-width: 400px)";
    "not all and (monochrome)";
    "screen and (min-width: 400px) and (max-width: 800px)";
  ]

(* CSSOM sec. 4.1: an empty media query list matches every medium, which is what
   [@media { }] and [matchMedia("")] both ask about. *)
let empty_query = [ "" ]

let lists =
  [
    "screen, print";
    "print, screen";
    "(min-width: 400px), (orientation: portrait)";
    "print, (min-width: 400px)";
    "(cascade-unknown: 1), screen";
    "(width: banana), (min-width: 400px)";
    "screen and (min-width: 400px), (max-width: 300px)";
    "not screen, (min-width: 400px)";
  ]

let atoms =
  List.concat
    [
      bounds "width" width_values;
      bounds "height" height_values;
      intervals;
      discrete;
      booleans;
      numerics;
    ]

let compound_count = 220

(* Media Queries 4 sec. 3: [and] and [or] do not mix at one level without a
   wrapper, and every operand of [not] is a [<media-in-parens>], so the shapes
   below are the ones the grammar writes. *)
let compounds s =
  List.init compound_count (fun _ ->
      let a () = pick s atoms in
      match next s mod 8 with
      | 0 -> String.concat "" [ a (); " and "; a () ]
      | 1 -> String.concat "" [ a (); " or "; a () ]
      | 2 -> String.concat "" [ "not "; a () ]
      | 3 -> String.concat "" [ a (); " and "; a (); " and "; a () ]
      | 4 -> String.concat "" [ "("; a (); " or "; a (); ") and "; a () ]
      | 5 -> String.concat "" [ a (); ", "; a () ]
      | 6 -> String.concat "" [ "screen and "; a (); " and "; a () ]
      | _ -> String.concat "" [ "not ("; a (); " and "; a (); ")" ])

let media_seeds ~seed =
  let s = stream seed in
  List.concat
    [
      atoms;
      empty_query;
      bound_pairs;
      unrecognised;
      recovery;
      types;
      lists;
      compounds s;
    ]

(* ===== The [@supports] population ===== *)

let supports_leaves =
  [
    "(display: grid)";
    "(display: flex)";
    "(display: cascade-nope)";
    "(color: red)";
    "(color: #f00)";
    "(color: color-mix(in oklab, red, blue))";
    "(width: 10px)";
    "(width: stretch)";
    "(height: stretch)";
    "(gap: 1px)";
    "(aspect-ratio: 1/1)";
    "(position: sticky)";
    "(position: cascade-nope)";
    "(transform: translate(1px))";
    "(text-wrap: balance)";
    "(anchor-name: --a)";
    "(background: linear-gradient(red, blue))";
    "(cascade-nope: 1)";
    "(--custom: 1)";
    "(all: initial)";
    "(color: var(--x))";
    "selector(:has(a))";
    "selector(a > b)";
    "selector(:cascade-nope)";
    "selector(::before)";
    "selector(a || b)";
    "font-format(woff2)";
    "font-format(opentype)";
    "font-format(cascade-nope)";
    "font-tech(variations)";
    "font-tech(color-COLRv1)";
    "font-tech(cascade-nope)";
    "at-rule(@media)";
  ]

let supports_compound_count = 140

let supports_seeds ~seed =
  let s = stream (seed + 7919) in
  let a () = pick s supports_leaves in
  let generated =
    List.init supports_compound_count (fun _ ->
        match next s mod 7 with
        | 0 -> String.concat "" [ a (); " and "; a () ]
        | 1 -> String.concat "" [ a (); " or "; a () ]
        | 2 -> String.concat "" [ "not "; a () ]
        | 3 -> String.concat "" [ a (); " and "; a (); " and "; a () ]
        | 4 -> String.concat "" [ "("; a (); " or "; a (); ") and "; a () ]
        | 5 -> String.concat "" [ "not ("; a (); " and "; a (); ")" ]
        | _ -> String.concat "" [ "(("; a (); ") or ("; a (); "))" ])
  in
  List.concat [ supports_leaves; generated ]

(* ===== The [@container] population ===== *)

(* A host is a container and the probe inside it. The features cascade is told
   about are the ones the container type makes queryable: an [inline-size]
   container answers about its inline axis only (Conditional Rules 5 sec.
   5.1). *)
type host = {
  host_id : string;
  container_name : string;
  style : string;
  width : float;
  height : float option;
  props : (string * string) list;
}

let hosts =
  List.mapi
    (fun i h -> { h with host_id = string_of_int i })
    [
      {
        host_id = "";
        container_name = "cn";
        style =
          "container-type: size; container-name: cn; width: 500px; height: \
           300px; --gap: 10px; --flag: 1";
        width = 500.;
        height = Some 300.;
        props = [ ("--gap", "10px"); ("--flag", "1") ];
      };
      {
        host_id = "";
        container_name = "cn";
        style =
          "container-type: size; container-name: cn; width: 399px; height: \
           300px; --gap: 20px";
        width = 399.;
        height = Some 300.;
        props = [ ("--gap", "20px") ];
      };
      {
        host_id = "";
        container_name = "cn";
        style =
          "container-type: size; container-name: cn; width: 400px; height: \
           300px; --gap: 10px";
        width = 400.;
        height = Some 300.;
        props = [ ("--gap", "10px") ];
      };
      {
        host_id = "";
        container_name = "cn";
        style =
          "container-type: size; container-name: cn; width: 401px; height: \
           500px";
        width = 401.;
        height = Some 500.;
        props = [];
      };
      {
        host_id = "";
        container_name = "cn";
        style = "container-type: inline-size; container-name: cn; width: 500px";
        width = 500.;
        height = None;
        props = [];
      };
      {
        host_id = "";
        container_name = "other";
        style =
          "container-type: size; container-name: other; width: 500px; height: \
           300px";
        width = 500.;
        height = Some 300.;
        props = [];
      };
    ]

let container_seeds =
  [
    "cn (min-width: 400px)";
    "cn (width >= 400px)";
    "cn (max-width: 400px)";
    "cn (width < 400px)";
    "cn (min-inline-size: 400px)";
    "cn (inline-size > 400px)";
    "cn (min-height: 300px)";
    "cn (block-size: 300px)";
    "cn (height >= 300px)";
    "cn (400px <= width <= 600px)";
    "cn (min-width: 400px) and (max-width: 600px)";
    "cn (min-width: 400px) and (min-height: 300px)";
    "cn (min-width: 400px) or (min-height: 900px)";
    "cn not (min-width: 400px)";
    "cn (orientation: landscape)";
    "cn (orientation: portrait)";
    "cn (aspect-ratio: 5/3)";
    "cn (min-aspect-ratio: 1/1)";
    "cn style(--flag: 1)";
    "cn style(--flag: 2)";
    "cn style(--gap: 10px)";
    "cn style(--gap:10px)";
    "cn style(--gap)";
    "cn not style(--flag: 1)";
    "cn style(--flag: 1) and style(--gap: 10px)";
    "cn style(--flag: 1) or style(--gap: 99px)";
    "cn scroll-state(stuck: top)";
    "cn not scroll-state(stuck: top)";
    "(min-width: 400px)";
    "(max-width: 400px)";
    "(min-width: 400px) and (min-height: 300px)";
    "other (min-width: 400px)";
    "cascade-absent (min-width: 400px)";
    "cn (cascade-unknown: 1)";
    "cn not (cascade-unknown: 1)";
    "cn (width: banana)";
  ]

(* ===== Nesting ===== *)

(* CSS Conditional 3 sec. 3: a conditional group rule inside another applies
   where both conditions do, so a nested pair is the conjunction. *)
let nested_count = 40

let nested_seeds ~seed media supports =
  let s = stream (seed + 104729) in
  List.filter
    (fun (sup, med) -> (not (String.equal sup "")) && not (String.equal med ""))
    (List.init nested_count (fun _ -> (pick s supports, pick s media)))

(* ===== What a job may say ===== *)

(* A condition has to survive being written into a stylesheet, so anything
   carrying the sheet's own punctuation is not a condition this run can ask
   about. *)
let writable text =
  (not (String.equal text ""))
  && String.length text <= 400
  && not
       (String.exists
          (fun c ->
            Char.equal c ';' || Char.equal c '{' || Char.equal c '}'
            || Char.equal c '\n' || Char.equal c '\r' || Char.equal c '\\')
          text)

(* An empty media query list is a query, so the media population is the one
   place the empty text is a member rather than a gap. *)
let writable_media text = String.equal text "" || writable text

(* ===== The driver ===== *)

let read_lines ic =
  let rec loop acc =
    match input_line ic with
    | line -> loop (line :: acc)
    | exception End_of_file -> List.rev acc
  in
  loop []

let run_driver ~node ~chrome ~script ~jobs ~work =
  let errors = work // "at-rule-conditions.err" in
  let cmd =
    String.concat " "
      [
        String.concat "" [ "CHROME="; Filename.quote chrome ];
        Filename.quote node;
        Filename.quote script;
        Filename.quote jobs;
        Filename.quote work;
        String.concat "" [ "2>"; Filename.quote errors ];
      ]
  in
  let ic = Unix.open_process_in cmd in
  let lines = read_lines ic in
  match Unix.close_process_in ic with
  | Unix.WEXITED 0 -> Ok lines
  | Unix.WEXITED _ | Unix.WSIGNALED _ | Unix.WSTOPPED _ ->
      let ic = open_in errors in
      let text = read_lines ic in
      close_in ic;
      Error (String.concat "\n" text)

(* ===== The browser's answers ===== *)

type answer = { primary : bool; applied : bool }

let discovered : (string * string, string) Hashtbl.t = Hashtbl.create 512
let media_answers : (string * string, answer) Hashtbl.t = Hashtbl.create 65536
let nested_answers : (string * string, bool) Hashtbl.t = Hashtbl.create 4096
let supports_answers : (string, answer) Hashtbl.t = Hashtbl.create 1024
let container_answers : (string * string, bool) Hashtbl.t = Hashtbl.create 4096
let driver_errors : (string * string) list ref = ref []
let bit s = String.equal s "1"

let parse_driver_output lines =
  List.iter
    (fun line ->
      match String.split_on_char '\t' line with
      | [ "e"; env; feature; value ] ->
          Hashtbl.replace discovered (env, feature) value
      | [ "m"; env; id; primary; applied ] ->
          Hashtbl.replace media_answers (env, id)
            { primary = bit primary; applied = bit applied }
      | [ "n"; env; id; applied ] ->
          Hashtbl.replace nested_answers (env, id) (bit applied)
      | [ "s"; id; primary; applied ] ->
          Hashtbl.replace supports_answers id
            { primary = bit primary; applied = bit applied }
      | [ "c"; host; id; applied ] ->
          Hashtbl.replace container_answers (host, id) (bit applied)
      | "x" :: scope :: rest ->
          driver_errors := (scope, String.concat "\t" rest) :: !driver_errors
      | _ -> ())
    lines

(* ===== The query context, built out of what the browser reported ===== *)

(* "?" is unknown; "-" is recognized but matches no value. Keep these states
   distinct in the explicit context, since negation distinguishes them. A
   feature reporting multiple keywords is a threshold feature; the first value
   is taken and the reading is reported. *)
let env_reading env =
  let entries =
    Hashtbl.fold
      (fun (e, feature) value acc ->
        if String.equal e env then (feature, value) :: acc else acc)
      discovered []
  in
  List.sort (fun (a, _) (b, _) -> String.compare a b) entries

let table_of_env env =
  List.filter_map
    (fun (feature, value) ->
      if String.equal value "?" || String.equal value "-" then None
      else
        let value =
          match String.index_opt value ',' with
          | Some i -> String.sub value 0 i
          | None -> value
        in
        match Media.feature feature (Media.value_of_string value) with
        | exception _ -> None
        | entry -> Some entry)
    (env_reading env)

let thresholds env =
  List.filter (fun (_, value) -> String.contains value ',') (env_reading env)

(* ===== Parsing, guarded ===== *)

type media_job = { id : string; text : string; query : Media.t option }

let parse_media text =
  match Media.of_string text with exception _ -> None | q -> Some q

let parse_supports text =
  match Supports.of_string text with exception _ -> None | c -> Some c

let parse_container text =
  match Container.of_string text with exception _ -> None | c -> Some c

let supports_leaf (c : Supports.t) =
  match c with Property _ | Function _ -> true | Not _ | And _ | Or _ -> false

(* A rewrite is checked by asking the browser about the rewritten text, so the
   rewrite joins the population. Reading the query back out of the parser is a
   stage of its own, and the first one: a query the parser recovers to [not all]
   has already lost what it selected before any rewrite runs, and attributing
   that to the rewrite would name the wrong function. *)
let serialise q =
  match Media.to_string ~minify:true q with
  | exception _ -> None
  | text -> Some text

let rewrites_of = function
  | None -> []
  | Some q ->
      List.filter_map
        (fun (label, rewritten) ->
          Option.map (fun text -> (label, text)) (serialise rewritten))
        [
          ("round_trip", q);
          ("lower_for_minify", Media.lower_for_minify q);
          ("normalize", Media.normalize q);
        ]

(* ===== Judging ===== *)

type verdict = Agree | Disagree | Split

let judge ~cascade answer =
  if not (Bool.equal answer.primary answer.applied) then Split
  else if Bool.equal cascade answer.primary then Agree
  else Disagree

let verdict_name = function
  | Agree -> "agree"
  | Disagree -> "disagree"
  | Split -> "split"

(* The judge decides nothing about a condition, so putting made-up verdicts
   through it says whether the arm that reports a difference can fire at all. A
   run that reports nothing has to be a run that could have. *)
let check_judge () =
  let cases =
    [
      ("both say yes", true, { primary = true; applied = true }, "agree");
      ("both say no", false, { primary = false; applied = false }, "agree");
      ( "only the browser says yes",
        false,
        { primary = true; applied = true },
        "disagree" );
      ( "only cascade says yes",
        true,
        { primary = false; applied = false },
        "disagree" );
      ( "the oracles disagree",
        true,
        { primary = true; applied = false },
        "split" );
    ]
  in
  List.iter
    (fun (what, cascade, answer, expected) ->
      let got = verdict_name (judge ~cascade answer) in
      if not (String.equal got expected) then (
        Fmt.pr "FAIL the judge calls %s %s, not %s@." what got expected;
        exit 1))
    cases

(* ===== Findings ===== *)

type finding = { where : string; what : string; detail : string }

(* A merge finding is a whole equivalence class, not a pair: cascade calls the
   members one query, so what a browser that tells them apart produces is a
   partition of the class, and printing that once says more than printing every
   pair of it. *)
type merge_split = { normal : string; groups : (string * string list) list }

let evaluation : finding list ref = ref []
let rewriting : finding list ref = ref []
let merge_splits : merge_split list ref = ref []
let splits : finding list ref = ref []
let notes : string list ref = ref []
let failures = ref 0

let fail line =
  incr failures;
  Fmt.pr "FAIL %s@." line

(* One condition that comes out differently in six environments is one finding
   seen six times, so the environments are gathered onto the line rather than
   printed as six of them. *)
let report label findings =
  match findings with
  | [] -> ()
  | _ ->
      let table = Hashtbl.create 256 in
      let order = ref [] in
      List.iter
        (fun f ->
          let key = (f.what, f.detail) in
          match Hashtbl.find_opt table key with
          | None ->
              order := key :: !order;
              Hashtbl.replace table key [ f.where ]
          | Some l -> Hashtbl.replace table key (f.where :: l))
        (List.rev findings);
      Fmt.pr "@.%s: %d over %d distinct condition(s)@." label
        (List.length findings) (List.length !order);
      List.iter
        (fun (what, detail) ->
          let wheres =
            match Hashtbl.find_opt table (what, detail) with
            | Some l -> List.rev l
            | None -> []
          in
          Fmt.pr "  %s | %s | %s@." what detail (String.concat ", " wheres))
        (List.rev !order)

let report_merging () =
  match !merge_splits with
  | [] -> ()
  | found ->
      Fmt.pr
        "@.MERGING (cascade merges blocks the browser tells apart): %d \
         equivalence class(es)@."
        (List.length found);
      List.iter
        (fun split ->
          Fmt.pr "  class %s@." split.normal;
          List.iter
            (fun (vector, members) ->
              Fmt.pr "    %s : %s@." vector (String.concat " | " members))
            split.groups)
        (List.rev found)

(* ===== Arguments ===== *)

let default_seed = 0
let seed = ref default_seed
let only = ref None
let population_only = ref false
let plant = ref None

let usage () =
  Fmt.pr
    "usage: at_rule_conditions [--seed N] [--only SUBSTRING] [--population] \
     [--plant evaluation|rewrite|merge]@.";
  exit 0

let parse_args () =
  let rec loop i =
    if i >= Array.length Sys.argv then ()
    else
      match Sys.argv.(i) with
      | "--seed" when i + 1 < Array.length Sys.argv ->
          seed := int_of_string Sys.argv.(i + 1);
          loop (i + 2)
      | "--only" when i + 1 < Array.length Sys.argv ->
          only := Some Sys.argv.(i + 1);
          loop (i + 2)
      | "--population" ->
          population_only := true;
          loop (i + 1)
      | "--plant" when i + 1 < Array.length Sys.argv ->
          plant := Some Sys.argv.(i + 1);
          loop (i + 2)
      | _ -> usage ()
  in
  loop 1

(* A wrong answer put into the comparison by hand, so a green run can be shown
   not to be a blind one. Each plant is one condition, so the report it produces
   is the report a real difference would produce. *)
let planted kind at =
  match !plant with Some k -> String.equal k kind && at | None -> false

let contains haystack needle =
  let n = String.length needle and h = String.length haystack in
  let rec at i =
    i + n <= h && (String.equal (String.sub haystack i n) needle || at (i + 1))
  in
  n = 0 || at 0

let selected text =
  match !only with None -> true | Some needle -> contains text needle

(* ===== Floors ===== *)

(* A run over an empty or shrunken population is a green run that asks nothing,
   which is worse than a red one. *)
let minimum_media = 300
let minimum_environments = 8
let minimum_media_observations = 3000
let minimum_supports = 100
let minimum_container_observations = 150
let minimum_true_media = 40

(* ===== Anchors ===== *)

(* Conditions no specification leaves room to argue about, whose agreement the
   run prints. If one of these comes out red the run is not reporting a defect
   in a corner, it is reporting that the harness has stopped working. *)
let anchors =
  [
    "(min-width: 0px)";
    "(width >= 0px)";
    "screen";
    "print";
    "not all";
    "all";
    "(min-width: 1024px)";
    "(orientation: portrait)";
    "(orientation: landscape)";
  ]

(* ===== Main ===== *)

let write_jobs file ~envs ~media ~nested ~supports ~hosts_json ~container =
  let oc = open_out file in
  output_string oc
    (Json.to_string
       (Json.Obj
          [
            ("envs", Json.Arr envs);
            ("media", Json.Arr media);
            ("nested", Json.Arr nested);
            ("supports", Json.Arr supports);
            ("hosts", Json.Arr hosts_json);
            ("container", Json.Arr container);
          ]));
  close_out oc

let () =
  parse_args ();
  check_judge ();

  (* --- the media population, and every rewrite of it --- *)
  let media_ids : (string, string) Hashtbl.t = Hashtbl.create 4096 in
  let media_by_id : (string, media_job) Hashtbl.t = Hashtbl.create 4096 in
  let order = ref [] in
  let counter = ref 0 in
  let intern text =
    match Hashtbl.find_opt media_ids text with
    | Some id -> Some id
    | None ->
        if not (writable_media text) then None
        else (
          incr counter;
          let id = string_of_int !counter in
          Hashtbl.replace media_ids text id;
          Hashtbl.replace media_by_id id { id; text; query = parse_media text };
          order := id :: !order;
          Some id)
  in
  let seed_ids =
    List.filter_map intern
      (List.sort_uniq String.compare
         (List.filter selected
            (List.filter writable_media (media_seeds ~seed:!seed))))
  in
  (* A rewrite is compared against the stage it was derived from: the parser's
     own serialisation against the source text, and each rewrite against that
     serialisation. *)
  let rewrite_pairs =
    List.concat_map
      (fun id ->
        let job = Hashtbl.find media_by_id id in
        let stages = rewrites_of job.query in
        let base =
          match
            List.find_map
              (fun (label, text) ->
                if String.equal label "round_trip" then Some text else None)
              stages
          with
          | Some text -> ( match intern text with Some r -> r | None -> id)
          | None -> id
        in
        List.filter_map
          (fun (label, text) ->
            let from = if String.equal label "round_trip" then id else base in
            match intern text with
            | Some rewritten when not (String.equal rewritten from) ->
                Some (label, from, rewritten)
            | Some _ | None -> None)
          stages)
      seed_ids
  in
  let media_jobs =
    List.rev_map (fun id -> Hashtbl.find media_by_id id) !order
  in
  let media_text id =
    match Hashtbl.find_opt media_by_id id with Some j -> j.text | None -> id
  in

  (* --- the supports population --- *)
  let supports_ids : (string, string) Hashtbl.t = Hashtbl.create 512 in
  let supports_order = ref [] in
  let supports_counter = ref 0 in
  let intern_supports text =
    match Hashtbl.find_opt supports_ids text with
    | Some id -> Some id
    | None ->
        if not (writable text) then None
        else (
          incr supports_counter;
          let id = string_of_int !supports_counter in
          Hashtbl.replace supports_ids text id;
          supports_order := (id, text) :: !supports_order;
          Some id)
  in
  (* The leaves are what the browser's answers build the supports table out of,
     so [--only] narrows the compounds and never the table: a table missing a
     leaf answers false about it and every compound over it. *)
  let supports_texts =
    List.sort_uniq String.compare
      (List.filter
         (fun t -> selected t || List.exists (String.equal t) supports_leaves)
         (List.filter writable (supports_seeds ~seed:!seed)))
  in
  List.iter (fun t -> ignore (intern_supports t)) supports_texts;

  (* [simplify_under] decides a guard against the conjunction enclosing it, and
     the decision it returns is itself a condition the browser has to answer
     about, so it joins the population before the browser is asked. *)
  let simplify_sample = ref [] in
  let pool = Array.of_list supports_texts in
  let s = stream (!seed + 15485863) in
  if Array.length pool > 1 then
    for _ = 1 to 600 do
      let k = pool.(next s mod Array.length pool) in
      let c = pool.(next s mod Array.length pool) in
      match (parse_supports k, parse_supports c) with
      | Some kc, Some cc -> (
          match Supports.simplify_under ~context:[ kc ] cc with
          | exception _ -> ()
          | decision ->
              (match decision with
              | `Cond c' -> (
                  match Supports.to_string c' with
                  | exception _ -> ()
                  | text -> ignore (intern_supports text))
              | `True | `False -> ());
              simplify_sample := (k, c, decision) :: !simplify_sample)
      | _ -> ()
    done;
  let supports_jobs = List.rev !supports_order in

  (* --- the container population --- *)
  let container_texts =
    List.sort_uniq String.compare
      (List.filter selected (List.filter writable container_seeds))
  in
  let container_jobs =
    ref (List.mapi (fun i t -> (string_of_int i, t)) container_texts)
  in
  let container_id text =
    List.find_map
      (fun (id, t) -> if String.equal t text then Some id else None)
      !container_jobs
  in
  let intern_container text =
    match container_id text with
    | Some id -> Some id
    | None ->
        if not (writable text) then None
        else
          let id = string_of_int (List.length !container_jobs) in
          container_jobs := !container_jobs @ [ (id, text) ];
          Some id
  in
  let container_rewrites =
    List.filter_map
      (fun (id, text) ->
        match parse_container text with
        | None -> None
        | Some c -> (
            match
              Container.to_stylesheet_string ~minify:true
                (Container.lower_for_minify c)
            with
            | exception _ -> None
            | rewritten -> (
                if String.equal rewritten text then None
                else
                  match intern_container rewritten with
                  | Some rid when not (String.equal rid id) ->
                      Some (id, rid, rewritten)
                  | Some _ | None -> None)))
      (List.map (fun (id, t) -> (id, t)) !container_jobs)
  in
  let container_text id =
    match List.find_opt (fun (i, _) -> String.equal i id) !container_jobs with
    | Some (_, t) -> t
    | None -> id
  in

  (* --- the nested population --- *)
  let nested =
    List.mapi
      (fun i (sup, med) -> (string_of_int i, sup, med))
      (nested_seeds ~seed:!seed
         (List.map (fun j -> j.text) media_jobs)
         (List.map snd supports_jobs))
  in

  if !population_only then (
    Fmt.pr
      "at_rule_conditions: %d media condition(s) over %d environment(s), %d \
       supports, %d container over %d host(s), %d nested, seed %d@."
      (List.length media_jobs) (List.length environments)
      (List.length supports_jobs)
      (List.length !container_jobs)
      (List.length hosts) (List.length nested) !seed;
    exit 0);

  if Option.is_some (Browser.getenv "CASCADE_NO_BROWSER") then
    Browser.skip "at_rule_conditions" "CASCADE_NO_BROWSER is set";
  let node =
    match Browser.node_binary () with
    | Some n -> n
    | None -> Browser.skip "at_rule_conditions" "no node"
  in
  let chrome =
    match Browser.chrome_binary () with
    | Some c -> c
    | None -> Browser.skip "at_rule_conditions" "no headless browser"
  in
  let script_dir = Filename.dirname Sys.executable_name in
  let work = Filename.get_temp_dir_name () // "cascade-at-rule-conditions" in
  (try Unix.mkdir work 0o755 with Unix.Unix_error (Unix.EEXIST, _, _) -> ());
  let jobs_file = work // "jobs.json" in
  let pair id text =
    Json.Obj [ ("id", Json.Str id); ("text", Json.Str text) ]
  in
  write_jobs jobs_file
    ~envs:
      (List.map
         (fun e ->
           Json.Obj
             [
               ("id", Json.Str e.env_id);
               ("flags", Json.Arr (List.map (fun f -> Json.Str f) e.flags));
             ])
         environments)
    ~media:(List.map (fun j -> pair j.id j.text) media_jobs)
    ~nested:
      (List.map
         (fun (id, sup, med) ->
           Json.Obj
             [
               ("id", Json.Str id);
               ("supports", Json.Str sup);
               ("media", Json.Str med);
             ])
         nested)
    ~supports:(List.map (fun (id, text) -> pair id text) supports_jobs)
    ~hosts_json:
      (List.map
         (fun h ->
           Json.Obj [ ("id", Json.Str h.host_id); ("style", Json.Str h.style) ])
         hosts)
    ~container:(List.map (fun (id, text) -> pair id text) !container_jobs);
  let started = Unix.gettimeofday () in
  let lines =
    match
      run_driver ~node ~chrome
        ~script:(script_dir // "at_rule_conditions.js")
        ~jobs:jobs_file ~work
    with
    | Ok lines -> lines
    | Error err ->
        prerr_endline
          (String.concat ""
             [ "at_rule_conditions: the browser driver failed:\n"; err ]);
        exit 1
  in
  let elapsed = Unix.gettimeofday () -. started in
  parse_driver_output lines;
  List.iter
    (fun (scope, message) ->
      fail (String.concat "" [ "the page failed in "; scope; ": "; message ]))
    !driver_errors;

  (* --- the environments, as the browser reported them --- *)
  let contexts =
    List.map
      (fun e ->
        let features = table_of_env e.env_id in
        let media_inapplicable =
          List.filter_map
            (fun (name, value) ->
              if String.equal value "-" then Some (Media.name_of_string name)
              else None)
            (env_reading e.env_id)
        in
        ( e,
          features,
          Context.query ~media_type:"screen" ~media_features:features
            ~media_inapplicable () ))
      environments
  in
  List.iter
    (fun (e, features, _) ->
      if List.length features < 8 then
        fail
          (String.concat ""
             [
               "environment ";
               e.env_id;
               " reported ";
               string_of_int (List.length features);
               " features, so the browser was not asked what it is";
             ]);
      List.iter
        (fun (feature, value) ->
          notes :=
            String.concat ""
              [
                "environment ";
                e.env_id;
                " reports more than one keyword for ";
                feature;
                ": ";
                value;
                "; a query context holds one value per feature, so a threshold \
                 feature cannot be stood for";
              ]
            :: !notes)
        (thresholds e.env_id))
    contexts;

  (* --- evaluation --- *)
  let observations = ref 0 in
  let true_somewhere = Hashtbl.create 1024 in
  let disagreed = Hashtbl.create 256 in
  List.iter
    (fun (e, _, ctx) ->
      let where = String.concat "" [ "env "; e.env_id ] in
      List.iter
        (fun job ->
          match Hashtbl.find_opt media_answers (e.env_id, job.id) with
          | None ->
              fail
                (String.concat ""
                   [
                     "the browser did not answer about ";
                     job.text;
                     " in environment ";
                     e.env_id;
                   ])
          | Some answer -> (
              incr observations;
              if answer.primary then Hashtbl.replace true_somewhere job.id ();
              let cascade =
                match job.query with
                | None -> false
                | Some q -> (
                    match Context.matches_media ctx q with
                    | exception _ -> false
                    | b -> b)
              in
              let cascade =
                if planted "evaluation" (String.equal job.text "screen") then
                  not cascade
                else cascade
              in
              match judge ~cascade answer with
              | Agree -> ()
              | Split ->
                  splits :=
                    {
                      where;
                      what = job.text;
                      detail =
                        String.concat ""
                          [
                            "matchMedia ";
                            string_of_bool answer.primary;
                            ", the rule ";
                            string_of_bool answer.applied;
                          ];
                    }
                    :: !splits
              | Disagree ->
                  Hashtbl.replace disagreed job.text ();
                  evaluation :=
                    {
                      where;
                      what = job.text;
                      detail =
                        String.concat ""
                          [
                            "cascade ";
                            string_of_bool cascade;
                            ", the browser ";
                            string_of_bool answer.primary;
                          ];
                    }
                    :: !evaluation))
        media_jobs)
    contexts;

  (* --- rewriting --- *)
  List.iter
    (fun (label, before, after) ->
      List.iter
        (fun (e, _, _) ->
          match
            ( Hashtbl.find_opt media_answers (e.env_id, before),
              Hashtbl.find_opt media_answers (e.env_id, after) )
          with
          | Some a, Some b ->
              let differ =
                (not (Bool.equal a.primary b.primary))
                || planted "rewrite"
                     (String.equal (media_text before)
                        "(min-width: 400px) and (max-width: 800px)")
              in
              if differ then
                rewriting :=
                  {
                    where = String.concat "" [ "env "; e.env_id ];
                    what = String.concat "" [ label; ": "; media_text before ];
                    detail =
                      String.concat ""
                        [
                          "becomes ";
                          media_text after;
                          "; the browser says ";
                          string_of_bool a.primary;
                          " before and ";
                          string_of_bool b.primary;
                          " after";
                        ];
                  }
                  :: !rewriting
          | _ -> ())
        contexts)
    rewrite_pairs;

  (* --- merging --- *)
  (* [Media.equal] is structural equality on normalised queries, so two queries
     it calls equal serialise their normal forms alike. Bucketing by that
     serialisation is a superset of the equality classes, and the pairs inside
     one bucket are the only ones worth asking [equal] about. *)
  let buckets = Hashtbl.create 1024 in
  List.iter
    (fun job ->
      match job.query with
      | None -> ()
      | Some q -> (
          match Media.to_string ~minify:true (Media.normalize q) with
          | exception _ -> ()
          | key ->
              let previous =
                match Hashtbl.find_opt buckets key with
                | Some l -> l
                | None -> []
              in
              Hashtbl.replace buckets key (job :: previous)))
    media_jobs;
  let answer_vector job =
    let buf = Buffer.create (List.length environments) in
    List.iter
      (fun (e, _, _) ->
        Buffer.add_char buf
          (match Hashtbl.find_opt media_answers (e.env_id, job.id) with
          | Some a -> if a.primary then '1' else '0'
          | None -> '?'))
      contexts;
    let vector = Buffer.contents buf in
    if planted "merge" (String.equal job.text "(min-width: 400px)") then
      String.map (fun c -> if Char.equal c '0' then '1' else '0') vector
    else vector
  in
  let merge_pairs = ref 0 in
  Hashtbl.iter
    (fun normal members ->
      (* Bucketing by the normal form is a superset of the equality classes, so
         the members are partitioned by [Media.equal] before their answers are
         compared. *)
      let classes = ref [] in
      List.iter
        (fun job ->
          match job.query with
          | None -> ()
          | Some q ->
              let rec place = function
                | [] -> classes := ref [ job ] :: !classes
                | c :: rest -> (
                    match !c with
                    | { query = Some r; _ } :: _ when Media.equal r q ->
                        c := job :: !c
                    | _ -> place rest)
              in
              place !classes)
        members;
      List.iter
        (fun c ->
          let members = List.rev !c in
          let n = List.length members in
          merge_pairs := !merge_pairs + (n * (n - 1) / 2);
          let vectors = Hashtbl.create 4 in
          let order = ref [] in
          List.iter
            (fun job ->
              let v = answer_vector job in
              match Hashtbl.find_opt vectors v with
              | None ->
                  order := v :: !order;
                  Hashtbl.replace vectors v [ job.text ]
              | Some l -> Hashtbl.replace vectors v (job.text :: l))
            members;
          if Hashtbl.length vectors > 1 then
            merge_splits :=
              {
                normal;
                groups =
                  List.rev_map
                    (fun v ->
                      ( v,
                        match Hashtbl.find_opt vectors v with
                        | Some l -> List.rev l
                        | None -> [] ))
                    !order;
              }
              :: !merge_splits)
        !classes)
    buckets;

  (* --- supports --- *)
  let supports_table =
    List.filter_map
      (fun (id, text) ->
        match (Hashtbl.find_opt supports_answers id, parse_supports text) with
        | Some a, Some c when a.primary && supports_leaf c -> Some c
        | _ -> None)
      supports_jobs
  in
  let supports_ctx = Context.query ~supports:supports_table () in
  let supports_cascade text =
    match parse_supports text with
    | None -> false
    | Some c -> (
        match Context.matches_supports supports_ctx c with
        | exception _ -> false
        | b -> b)
  in
  List.iter
    (fun (id, text) ->
      match Hashtbl.find_opt supports_answers id with
      | None ->
          fail
            (String.concat ""
               [ "the browser did not answer about @supports "; text ])
      | Some answer -> (
          let cascade = supports_cascade text in
          match judge ~cascade answer with
          | Agree -> ()
          | Split ->
              splits :=
                {
                  where = "@supports";
                  what = text;
                  detail =
                    String.concat ""
                      [
                        "CSS.supports ";
                        string_of_bool answer.primary;
                        ", the rule ";
                        string_of_bool answer.applied;
                      ];
                }
                :: !splits
          | Disagree ->
              evaluation :=
                {
                  where = "@supports";
                  what = text;
                  detail =
                    String.concat ""
                      [
                        "cascade ";
                        string_of_bool cascade;
                        ", the browser ";
                        string_of_bool answer.primary;
                      ];
                }
                :: !evaluation))
    supports_jobs;

  (* [simplify_under] claims a decision that holds for every user agent, so one
     browser can only refute it. The arms below are the three refutations a
     single agent can carry, and each needs the context to be true in it. *)
  let supports_truth text =
    match Hashtbl.find_opt supports_ids text with
    | None -> None
    | Some id -> (
        match Hashtbl.find_opt supports_answers id with
        | Some a -> Some a.primary
        | None -> None)
  in
  let simplify_checked = ref 0 in
  List.iter
    (fun (k, c, decision) ->
      match (supports_truth k, supports_truth c) with
      | Some true, Some bc ->
          incr simplify_checked;
          let violation =
            match decision with
            | `True ->
                if bc then None
                else
                  Some
                    "cascade splices the block in as always guarded, and the \
                     browser says the guard is false where the context holds"
            | `False ->
                if bc then
                  Some
                    "cascade drops the block as unreachable, and the browser \
                     says both the context and the guard hold"
                else None
            | `Cond c' -> (
                match Supports.to_string c' with
                | exception _ -> None
                | text -> (
                    match supports_truth text with
                    | Some bc' when not (Bool.equal bc bc') ->
                        Some
                          (String.concat ""
                             [
                               "cascade narrows the guard to ";
                               text;
                               ", and the browser answers ";
                               string_of_bool bc';
                               " to that and ";
                               string_of_bool bc;
                               " to the original";
                             ])
                    | _ -> None))
          in
          Option.iter
            (fun detail ->
              evaluation :=
                {
                  where = "simplify_under";
                  what = String.concat "" [ c; "  under  "; k ];
                  detail;
                }
                :: !evaluation)
            violation
      | _ -> ())
    !simplify_sample;

  (* --- container --- *)
  let container_observations = ref 0 in
  List.iter
    (fun h ->
      let features =
        List.concat
          [
            [
              Container.feature "width" (Media.Length (Values.Px h.width));
              Container.feature "inline-size" (Media.Length (Values.Px h.width));
            ];
            (match h.height with
            | None -> []
            | Some height ->
                [
                  Container.feature "height" (Media.Length (Values.Px height));
                  Container.feature "block-size"
                    (Media.Length (Values.Px height));
                  Container.feature "orientation"
                    (Media.Ident
                       (if h.width >= height then Media.Landscape
                        else Media.Portrait));
                  Container.feature "aspect-ratio"
                    (Media.Ratio (int_of_float h.width, int_of_float height));
                ]);
            List.map (fun (name, value) -> Container.style ~value name) h.props;
          ]
      in
      let ctx =
        Context.query ~container_name:h.container_name
          ~container_features:features ()
      in
      List.iter
        (fun (id, text) ->
          match Hashtbl.find_opt container_answers (h.host_id, id) with
          | None ->
              fail
                (String.concat ""
                   [
                     "the browser did not answer about @container ";
                     text;
                     " for host ";
                     h.host_id;
                   ])
          | Some browser ->
              incr container_observations;
              let cascade =
                match parse_container text with
                | None -> false
                | Some c -> (
                    match Context.matches_container ctx c with
                    | exception _ -> false
                    | b -> b)
              in
              if not (Bool.equal cascade browser) then
                evaluation :=
                  {
                    where = String.concat "" [ "@container host "; h.host_id ];
                    what = text;
                    detail =
                      String.concat ""
                        [
                          "cascade ";
                          string_of_bool cascade;
                          ", the browser ";
                          string_of_bool browser;
                          "; the container is ";
                          h.style;
                        ];
                  }
                  :: !evaluation)
        !container_jobs)
    hosts;
  List.iter
    (fun (before, after, text) ->
      List.iter
        (fun h ->
          match
            ( Hashtbl.find_opt container_answers (h.host_id, before),
              Hashtbl.find_opt container_answers (h.host_id, after) )
          with
          | Some x, Some y when not (Bool.equal x y) ->
              rewriting :=
                {
                  where = String.concat "" [ "@container host "; h.host_id ];
                  what =
                    String.concat ""
                      [ "lower_for_minify: "; container_text before ];
                  detail =
                    String.concat ""
                      [
                        "becomes ";
                        text;
                        "; the browser says ";
                        string_of_bool x;
                        " before and ";
                        string_of_bool y;
                        " after";
                      ];
                }
                :: !rewriting
          | _ -> ())
        hosts)
    container_rewrites;

  (* --- nesting --- *)
  List.iter
    (fun (e, _, ctx) ->
      List.iter
        (fun (id, sup, med) ->
          match Hashtbl.find_opt nested_answers (e.env_id, id) with
          | None -> ()
          | Some browser ->
              let cascade =
                match parse_media med with
                | None -> false
                | Some mc -> (
                    match Context.matches_media ctx mc with
                    | exception _ -> false
                    | b -> b && supports_cascade sup)
              in
              if not (Bool.equal cascade browser) then
                evaluation :=
                  {
                    where = String.concat "" [ "nested env "; e.env_id ];
                    what =
                      String.concat ""
                        [ "@supports "; sup; " { @media "; med; " }" ];
                    detail =
                      String.concat ""
                        [
                          "cascade ";
                          string_of_bool cascade;
                          ", the browser ";
                          string_of_bool browser;
                        ];
                  }
                  :: !evaluation)
        nested)
    contexts;

  (* --- what the run asked --- *)
  Fmt.pr
    "at_rule_conditions: %d media condition(s) x %d environment(s) = %d \
     observation(s), seed %d, %.1fs@."
    (List.length media_jobs) (List.length environments) !observations !seed
    elapsed;
  Fmt.pr
    "  %d supports condition(s), %d simplify_under decision(s) the browser can \
     refute, %d container observation(s) over %d host(s), %d nested@."
    (List.length supports_jobs)
    !simplify_checked !container_observations (List.length hosts)
    (List.length nested);
  Fmt.pr "  %d media condition(s) hold somewhere, %d pair(s) cascade merges@."
    (Hashtbl.length true_somewhere)
    !merge_pairs;
  (* A merge finding names its environments by position in this list, so the
     list has to be printed for the vector to be readable. *)
  List.iter (fun (e, _, _) -> Fmt.pr "  env %s: %s@." e.env_id e.label) contexts;
  List.iter
    (fun (feature, value) -> Fmt.pr "  environment 0: %s = %s@." feature value)
    (env_reading "0");
  List.iter (fun n -> Fmt.pr "  note: %s@." n) (List.rev !notes);
  List.iter
    (fun text ->
      match Hashtbl.find_opt media_ids text with
      | None ->
          fail
            (String.concat ""
               [
                 "the anchor ";
                 text;
                 " left the population, so a green run proves less";
               ])
      | Some _ ->
          Fmt.pr "  anchor: %s -> %s@." text
            (if Hashtbl.mem disagreed text then "DISAGREED" else "agreed"))
    anchors;

  (match !only with
  | Some _ -> ()
  | None ->
      if List.length media_jobs < minimum_media then
        fail
          (String.concat ""
             [
               "the generator yielded ";
               string_of_int (List.length media_jobs);
               " media conditions, fewer than the ";
               string_of_int minimum_media;
               " expected";
             ]);
      if List.length environments < minimum_environments then
        fail "the environment list shrank below what a boundary needs";
      if !observations < minimum_media_observations then
        fail
          (String.concat ""
             [
               "only ";
               string_of_int !observations;
               " media observations, fewer than the ";
               string_of_int minimum_media_observations;
               " expected";
             ]);
      if List.length supports_jobs < minimum_supports then
        fail "the supports population shrank";
      if !container_observations < minimum_container_observations then
        fail "the container population shrank";
      (* A population of nothing but conditions that never hold agrees about all
         of it and asks nothing. *)
      if Hashtbl.length true_somewhere < minimum_true_media then
        fail
          (String.concat ""
             [
               "only ";
               string_of_int (Hashtbl.length true_somewhere);
               " media conditions hold in any environment, fewer than the ";
               string_of_int minimum_true_media;
               " expected";
             ]));

  report "EVALUATION (cascade and the browser disagree that the block applies)"
    !evaluation;
  report "REWRITING (a rewrite changed which media the query selects)"
    !rewriting;
  report_merging ();
  report "ORACLE SPLIT (the two browser oracles disagree)" !splits;
  let found =
    List.length !evaluation + List.length !rewriting + List.length !merge_splits
    + List.length !splits
  in
  if found > 0 || !failures > 0 then exit 1
